---
- name: Configuration des périphériques réseau
  hosts: routers
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
          - name: s0/0
            ipv4:
              - address: 192.168.0.1/24

